### ISSUE TITLE
Spring Expression Language cannot deal with non-latin characters

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#43]
This is an issue because we push pretty much all variables through SpEL.

Example:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello [$name]</title>
</head>
<body>
<h1>🦑 Hello [$name]</h1>
<p>Some example text.</p>
</body>
</html>
```

```
@UIEventPage(path = "/hello", file = "pages/hello-world.html")
public class HelloWorldEventHandler implements UIEventWithAttributes {

    @Override
    public PageAttributes setupAttributes(ServerRequest request, SecurityContext securityContext) {
        return new PageAttributes().with("name", "희영");
    }

}

```

Crashes with:

```
java.lang.IllegalStateException: Cannot handle (55148) '희'
	at org.springframework.expression.spel.standard.Tokenizer.process(Tokenizer.java:268)
	at org.springframework.expression.spel.standard.InternalSpelExpressionParser.doParseExpression(InternalSpelExpressionParser.java:127)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:61)
	at org.springframework.expression.spel.standard.SpelExpressionParser.doParseExpression(SpelExpressionParser.java:33)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpression(TemplateAwareExpressionParser.java:52)
	at org.springframework.expression.common.TemplateAwareExpressionParser.parseExpression(TemplateAwareExpressionParser.java:43)
	at io.getmedusa.medusa.core.util.SpelExpressionParserHelper.isExpression(SpelExpressionParserHelper.java:61)
	at io.getmedusa.medusa.core.util.ExpressionEval.eval(ExpressionEval.java:27)
	at io.getmedusa.medusa.core.injector.tag.ValueTag.replaceTitle(ValueTag.java:73)
	at io.getmedusa.medusa.core.injector.tag.ValueTag.injectWithVariables(ValueTag.java:18)
```

**Comment by kevindeyne** [comment]
Related: https://stackoverflow.com/questions/8571992/spel-cannot-handle-%C3%A9/8572009

**Comment by kevindeyne** [comment]
Managed to fix the most obvious problems described above. We should make sure we make every integration test also account for non-latin characters so this doesn't get missed.

**Comment by kevindeyne** [comment]
We should keep an eye on this as we progress, but for now I'm explicitly testing with some basic scenarios that rendering and passing values should work.
